export const TRADE_COLUMNS = (lcl) => [
  { key: '#',               label: '#',                              align: 'right', mono: true, decimals: 0 },
  { key: 'taxable',         label: 'Облагаем?',                     editable: 'checkbox' },
  { key: 'taxExemptLabel',  label: 'Данъчен статус',                chip: true, chipColors: { 'Освободен': 'success', 'Облагаем': 'default' } },
  { key: 'symbol',          label: 'Symbol',                        bold: true },
  { key: 'instrType',       label: 'Тип',                           chip: true, chipColors: { ETF: 'primary', Stock: 'default', Other: 'default' } },
  { key: 'securityId',      label: 'ISIN',                          tooltip: 'description' },
  { key: 'exchange',        label: 'Exchange' },
  { key: 'datetime',        label: 'Trade Date/Time',               mono: true },
  { key: 'currency',        label: 'Currency' },
  { key: 'side',            label: 'Type',                          chip: true, chipColors: { BUY: 'primary', SELL: 'secondary' } },
  { key: 'quantityDisplay', label: 'Quantity',                      align: 'right', mono: true },
  { key: 'price',           label: 'Price',                         align: 'right', mono: true },
  { key: 'proceeds',        label: 'Proceeds',                      align: 'right', mono: true, decimals: 2 },
  { key: 'commission',      label: 'Commission',                    align: 'right', mono: true, decimals: 2 },
  { key: 'fee',             label: 'Fee',                           align: 'right', mono: true, decimals: 2 },
  { key: 'totalWithFee',    label: 'Общо + такси (вал)',            align: 'right', mono: true, decimals: 2 },
  { key: 'rate',            label: `Курс (${lcl})`,                 align: 'right', mono: true, decimals: 5, nullAs: '—' },
  { key: 'totalWithFeeLcl', label: `Общо + такси (${lcl})`,         align: 'right', mono: true, decimals: 2, nullAs: '—' },
  { key: 'costBasis',       label: 'Цена на придобиване (вал)',     align: 'right', mono: true, decimals: 2, nullAs: '—' },
  { key: 'costBasisLcl',    label: `Цена на придобиване (${lcl})`,  align: 'right', mono: true, decimals: 2, nullAs: '—' },
]